name: Push Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      eureka:
        image: 'xdockerh/eureka-server:latest'
        ports:
          - 8761:8761

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check License Header
        uses: apache/skywalking-eyes/header@501a28d2fb4a9b962661987e50cf0219631b32ff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: typos-action
        uses: crate-ci/typos@v1.2.1

      - name: Lint
        run: |
          go vet -stdmethods=false $(go list ./...)
          go install mvdan.cc/gofumpt@v0.2.0
          test -z "$(gofumpt -l -extra .)" 

      - name: Unit Test
        run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...

      - name: Benchmark
        run: go test -bench=. -benchmem -run=none ./...
